from sources.models.digit_config import DigitConfig
from sources.models.main_config import MainConfig
from sources.models.plate_config import PlateConfig
from sources.models.data import DataRequest
from sources.models.plate import PlateResponse
from sources.models.digit import DigitResponse
from sources.models.plate_bs64 import PlateBs64Response
from sources.models.response_socket import SocketResponse
from sources.models.vehicle_config import VehicleConfig
from sources.models.vehicle import VehicleResponse
from sources.models.app_data import AppDataRequest
